config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root 'publics#home'

  resources :properties do
    collection do
      get :auction
      get :featureds, to: 'properties#featured'
      get 'wishlist/:id', to: 'properties#wishlist', as: 'wishlist'
      post :checkout_bid
    end
  end

  resources :projects do
    collection { get :featureds, to: 'projects#featureds' }
  end
  resources :users, only: [:show] do
    member do
      get :about_company
      get 'reviews', to: 'users#reviews'
      delete 'reviews/:rate_id', to: 'users#delete_reviews', as: 'delete_rate'
      post 'reviews', to: 'reviews#create'
    end
  end
  resources :landing_pages, only: [:show]
  resources :inquiries
  resources :feedbacks, only: [:create]
  resources :reports, only: [:create]
  resources :schedule_visits, only: [:create]

  get 'map',                          to: 'properties#map',             as: 'map'
  get 'list',                         to: 'properties#list',            as: 'list'
  get 'package',                      to: 'publics#package',            as: 'package'
  get 'get_societies',                to: 'publics#get_societies',      as: 'get_societies'

  get 'get_assets',                   to: 'xhrs#get_assets',            as: 'get_assets'
  get 'get_assets_property',          to: 'xhrs#get_assets_property',   as: 'get_assets_property'
  post 'save_assets_property',        to: 'xhrs#save_assets_property',  as: 'save_assets_property'
  get 'get_project_assets',           to: 'xhrs#get_project_assets',    as: 'get_project_assets'
  get 'get_assets_project',           to: 'xhrs#get_assets_projects',   as: 'get_assets_project'
  post 'save_assets_project',         to: 'xhrs#save_assets_project',   as: 'save_assets_project'
  get 'get_categories',               to: 'publics#get_categories',     as: 'get_categories'
  get 'cities_tag',                   to: 'publics#cities_tag',         as: 'cities_tag'
  get 'cities',                       to: 'xhrs#cities',                as: 'cities'
  get 'subdistricts',                 to: 'xhrs#subdistricts',          as: 'subdistricts'
  get 'village',                      to: 'xhrs#village',               as: 'village'
  get 'area',                         to: 'xhrs#area',                  as: 'area'
  get 'get_by_city',                  to: 'xhrs#get_by_city',           as: 'get_by_city'
  get 'get_properties_search',        to: 'xhrs#get_properties_search', as: 'get_properties_search'
  get '/get_detail_profile_property', to: 'xhrs#get_detail_properties', as: 'get_detail_profile_property'
  get '/get_detail_profile_project',  to: 'xhrs#get_detail_projects',   as: 'get_detail_profile_project'
  get '/label_packages',              to: 'xhrs#label_packages',        as: 'label_packages'

  get "autocomplete_region", to: "xhrs#autocomplete_region"
  get "autocomplete_auction_region", to: "xhrs#autocomplete_auction_region"

  resources :xhrs do
    collection do
      get :get_categories
      get :get_facilities
    end
  end

  namespace :backend do
    # The Role
    resources :roles, except: :show do
      patch 'change', on: :member
      resources :sections, controller: 'role_sections', only: :none do
        collection do
          post :create
          post :create_rule
          post :create_field

        end

        member do
          put :rule_on
          put :rule_off

          delete :destroy
          delete :destroy_rule
        end
      end
    end

    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :admins
    resources :members do
      collection do
        post :do_multiple_act
      end
    end
    resources :agents do
      collection do
        post :do_multiple_act
      end
    end
    resources :packages do
      collection do
        post :do_multiple_act
      end
    end
    resources :order_user_packages do
      member do
        patch '/confirmations', to: 'order_user_packages#confirmations'
      end
      collection do
        post '/multiple_confirmations', to: 'order_user_packages#multiple_confirmations'
      end
    end
    resources :developers do
      collection do
        post :do_multiple_act
      end
    end
    resources :properties do
      collection do
        post :do_multiple_act
        get :import, to: 'properties#import'
        post :do_import, to: 'properties#do_import'
        post :import, to: 'properties#do_import'
      end
    end
    resources :auction_properties do
      collection do
        post :do_multiple_act
      end
    end
    resources :property_types do
      collection do
        post :do_multiple_act
      end
    end
    resources :asset_facilities do
      collection do
        post :do_multiple_act
      end
    end
    resources :projects do
      collection do
        post :do_multiple_act
        get :import, to: 'projects#import'
        post :do_import, to: 'projects#do_import'
        post :import, to: 'projects#do_import'
      end
    end
    resources :locations do
      collection do
        post :do_multiple_act
      end
    end
    resources :supporteds do
      collection do
        post :do_multiple_act
      end
    end
    resources :testimonials do
      collection do
        post :do_multiple_act
      end
    end
    resources :feedbacks do
      collection do
        post :do_multiple_act
      end
    end
    resources :reports do
      collection do
        post :do_multiple_act
      end
    end
    resources :sold_reports do
      collection do
        post :do_multiple_act
      end
    end
    resources :regions
    resources :landing_pages
    resources :web_settings
  end

  namespace :userpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members do
      member do
        put :upgrade
      end
    end
    resources :agents, only: [:edit, :update, :show]
    resources :wishlists
    resources :inquiries
    resources :notifications
    resources :properties do
      member do
        put :renew
      end
      collection do
        post :do_report_sold
      end
    end
    resources :sold_reports
    resources :packages do
      collection do
        get :invoices
      end
      member do
        get :invoice
      end
    end
  end

  namespace :developerpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :developers, only: [:edit, :update, :show]
    resources :wishlists
    resources :inquiries
    resources :notifications
    resources :projects
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	extend FriendlyId
  friendly_id :username, use: [:slugged, :finders]
  after_create :send_welcome_mail

  include Ratyrate::Model
	include TheUser::UserConfig
	include TheUser::UserAuthenticate
	include TheUser::UserSearching
	include ScopeBased

  validates_uniqueness_of :code, if: 'self.code.present?'

  def package_payed?(package_id)
    user_packages.where(package_id: package_id).payed.present?
  end

  def label_packages
    user_packages.payed.not_expired.pluck(:label_tags).flatten.compact.join(',').split(',').uniq
  end

  def type_package
    type_package = packages.last.name == "Free Package" ? 'Free' : 'Premium'
  end

  def package_expire?(package_id)
    user_packages.where(package_id: package_id).expired.present?
  end

  def package_not_payed?(package_id)
    user_packages.where(package_id: package_id).not_payed.present?
  end

  def remain_listing
    current_package.max_listing - properties.count
  end

  def remain_featured_listing
    current_package.featured_listing - properties.featured.count
  end

  private
    def send_welcome_mail
      UserMailer.welcome_join(self).deliver
    end

end

app/controllers/backend/users_controller.rb
class Backend::UsersController < Backend::ApplicationController
	defaults resource_class: User, collection_name: 'users', instance_name: 'user'
	before_filter :prepare_selects!, only: [:new, :edit, :create, :update]
  before_action :role_required

	add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Users", :collection_path

	def index
		@collection = collection.search(params[:search]).latest.page(page).per(per_page)
	end

	protected
		def collection
			@collection ||= end_of_association_chain
		end

		def prepare_selects!
	    @cities_selects = City.all
		end
end

app/controllers/users_controller.rb
class UsersController < FrontendController
  layout 'detail'

  def show
    user
  	@lists = properties.latest.page(page).per(per_page)
  end

  def reviews
    user
    properties
    rating(user.id)
    render file: 'users/reviews'
  end

  def delete_reviews
    rate = Rate.find(params[:rate_id])
    if rate.delete
      flash[:success] = 'Your Rate Successfully Deleted'
    else
      flash[:error] = rate.errors.full_message
    end
    redirect_to reviews_user_path(params[:id])
  end

  def about_company
    user
  end

  protected
    def user
      @user ||= User.find(params[:id])
    end

    def properties
      @properties ||= if user.developer?
        properties = user.projects
      else
        properties = user.properties
      end
    end

    def rating(user_id)
      @reviews = Rate.where(rateable_id: user_id).page(page).per(per_page)
    end
end

app/views/shareds/users/_carousel_listing_property.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <div class="item-ratio item active">
      <img src="http://images.id.ippstatic.com/populer/populer-994-20150612033242.jpg">
    </div>
    <div class="item-ratio item">
      <img src="http://images.id.ippstatic.com/populer/populer-994-20150612033242.jpg">
    </div>
  </div>

  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shareds/users/_content.html.erb
<div class="content-users-middle">
  <div class="container">
    <div class="col-md-3">
      <%= render 'shareds/users/sidebar_left' %>
    </div>
    <div class="col-md-6">
      <div class="content-users">
        <div class="title-empty">
          It’s lonely here. :(
        </div>
        <div class="description-empty">
          Your activities will appear here.
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <%= render 'shareds/users/sidebar_right' %>
    </div>
  </div>
</div>

app/views/shareds/users/_cover_image.html.erb
<div class="cover-image-users">
  <div class="container">
    <div class="col-md-12">
      <div class="info-user-cover">
        <div class="col-md-1">
          <div class="user-image-cycle">
            <%= image_tag current_user.try(:profile).try(:avatar).url(:thumb) %>
          </div>
        </div>
        <div class="col-md-11">
          <div class="row">
            <div class="box-info-user">
              <div class="name">
                <%= current_user.try(:profile).try(:full_name) %>
              </div>
              <div class="email">
                <%= current_user.try(:email) %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= image_tag current_user.try(:profile).try(:cover).url(:large), class: 'img-responsive' %>
</div>

app/views/shareds/users/_description_listing_property.html.erb
<div class="col-md-12">
  <div class="negotiable">
    <i class="fa fa-check"></i>
    &nbsp;Negotiable
  </div>
  <div class="price">
    Rp. 1.000.000.000,-
  </div>
</div>

<div class="col-md-12">
  <div class="title">
    Apartemen kawasan griya sudirman estate ...
  </div>
</div>

<div class="col-md-12">
  <div class="horizontal-line"></div>
</div>

<div class="col-md-12">
  <div class="location-row">
    <div class="location">
      <i class="fa fa-map-marker"></i>
      <span>&nbsp;&nbsp;Jakarta Pusat</span>
    </div>
    <div class="label-catalog">
      <div class="label label-warning">
        Perumahan
      </div>
    </div>
  </div>
</div>

<div class="col-md-12">
  <div class="horizontal-line"></div>
</div>

<div class="col-md-12">
  <div class="info">
    <ul class="list-inline">
      <li>
        <i class="fa fa-tags"></i>
        &nbsp;12.876 m2
      </li>
      <li>
        <i class="fa fa-refresh"></i>
        &nbsp;12.876 m2
      </li>
      <li>
        <i class="fa fa-bars"></i>
        &nbsp;12.876 m2
      </li>
    </ul>
  </div>
</div>

<div class="col-md-12">
  <div class="location-row">
    <div class="location">
      <%= link_to root_path do %>
        &nbsp;&nbsp;View all
        <i class="fa fa-angle-down"></i>
      <% end %>
    </div>
    <div class="label-catalog">
      <div class="label label-primary">
        <i class="fa fa-eye"></i>
        &nbsp;View detail
      </div>
    </div>
  </div>
</div>

app/views/shareds/users/_menu.html.erb
<ul class="dropdown-menu">
  <li>
    <%= link_to userpage_dashboard_path do %>
      Dashboard <i class="fa fa-home pull-right"></i>
    <% end %>
  </li>
   <li class="divider"></li>
  <li>
    <%= link_to userpage_properties_path do %>
      Advertisements <i class="fa fa-image pull-right"></i>
    <% end %>
  </li>
  <li class="divider"></li>
  <li>
    <%= link_to userpage_wishlists_path do %>
      Wishlists <span class="glyphicon glyphicon-heart pull-right"></span>
    <% end %>
  </li>
  <li class="divider"></li>
  <li>
    <%= link_to user_edit_url(current_user.type, current_user) do %>
      Settings <span class="glyphicon glyphicon-cog pull-right"></span>
    <% end %>
  </li>
  <li class="divider"></li>
  <li>
    <%= link_to destroy_user_session_path, method: 'delete' do %>
      Sign Out <span class="glyphicon glyphicon-log-out pull-right"></span>
    <% end %>
  </li>
</ul>

app/views/shareds/users/_nav.html.erb
<nav class="navbar navbar-default <%= 'navbar-red' if params[:controller] == 'properties' && params[:action] == 'index' || params[:controller] == 'projects' && params[:action] == 'index' %> ">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'PROPEDIA', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if params[:controller] == 'properties' && params[:action] == 'index' || params[:controller] == 'projects' && params[:action] == 'index' %>
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Buy <span class="glyphicon glyphicon-menu-down"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Rent</a></li>
              <li><a href="#">PG &amp; Hotels</a></li>
              <li><a href="#">Sell</a></li>
              <li><a href="#">New Projects</a></li>
              <li><a href="#">Sell or Rent Property</a></li>
            </ul>
          </li>
        </ul>
        <form id="custom-search-input" class="form-search form-horizontal navbar-form navbar-left">
          <div class="input-group col-md-12">
            <input type="text" class="form-control" placeholder="Pencarian">
            <span class="input-group-btn">
              <button class="btn btn-info btn-search" type="button">
                <i class="glyphicon glyphicon-search"></i>
              </button>
            </span>
          </div>
        </form>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="">BLOG</a></li>
        <li><a href="">WE'RE HIRING</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            HELP &nbsp; &nbsp;<span class="glyphicon glyphicon-menu-down"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a href="#">Visit help center?</a>
            </li>
            <li>
              <a href="#">I'am a guest, what are some safety tips i can follow?</a>
            </li>
            <li>
              <a href="#">What's is Verified ID?</a>
            </li>
            <li>
              <a href="#">What's is Guarantee for Host?</a>
            </li>
            <li>
              <a href="#">See all faqs?</a>
            </li>
          </ul>
        </li>
        <li><a href="">SELL OR RENT PROPERTY</a></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-account dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
              <div class="user-image-cycle-top pull-left">
                <%= image_tag 'people1.jpg', class: "host-profile-image-top" %>
              </div>
              <span class="usr-name">Alam Topan &nbsp; &nbsp;<span class="glyphicon glyphicon-menu-down"></span></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to member_dashboard_path do %>
                  Dashboard <i class="fa fa-home pull-right"></i>
                <% end %>
              </li>
               <li class="divider"></li>
              <li>
                <a href="#">Advertisements <i class="fa fa-image pull-right"></i></a>
              </li>
              <li class="divider"></li>
              <li>
                <a href="#">Wishlists <span class="glyphicon glyphicon-heart pull-right"></span></a>
              </li>
              <li class="divider"></li>
              <li>
                <a href="#">Settings <span class="glyphicon glyphicon-cog pull-right"></span></a>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to destroy_user_session_path, method: 'delete' do %>
                  Sign Out <span class="glyphicon glyphicon-log-out pull-right"></span>
                <% end %>
              </li>
            </ul>
          </li>
          <li class="dropdown dropdown-account-message">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-comments fa-box-inbox"></i> <span class="count-inbox">22</span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <div class="header-inbox-pop">
                  <span class="pull-left"><small>Messages(10)</small></span>
                  <a href="#">
                    <span class="pull-right"><small>View Inbox</small></span>
                  </a>
                </div>
                <div class="box-inbox-pop">
                  No New Messages
                </div>
              </li>
              <li class="divider"></li>
              <li>
                <div class="header-inbox-pop">
                  <span class="pull-left"><small>Notifications(11)</small></span>
                  <a href="#">
                    <span class="pull-right"><small>See All</small></span>
                  </a>
                </div>
                <div class="box-inbox-pop">
                  No New Notifications
                </div>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <div class="btn-group btn-reg-log" role="group" aria-label="...">
              <%= link_to user_session_path, class: "btn btn-default left" do %>
                Sign In
              <% end %>
              <button type="button" class="btn btn-default cycle">OR</button>
              <%= link_to new_user_registration_path, class: "btn btn-default right" do %>
                Sign Up
              <% end %>
            </div>
          <li>
        <% end %>
        <%= render 'shareds/side_menu' %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if params[:controller] == 'properties' && params[:action] == 'index' %>
  <section class="form-top-search">
    <%= render 'shareds/properties/form_search' %>
  </section>
<% elsif params[:controller] == 'projects' && params[:action] == 'index' %>
  <section class="form-top-search">
    <%= render 'shareds/projects/form_search' %>
  </section>
<% end %>

app/views/shareds/users/_sidebar_left.html.erb
<div class="nav-sidebar-users-left">
  <nav class="nav-sidebar-left">
    <ul class="nav tabs">
      <li class="<%= active_sidebar_active?(:home, :dashboard) %>">
        <%= link_to userpage_dashboard_path do %>
          <i class="fa fa-home"></i>
          &nbsp;&nbsp;Dashboard
        <% end %>
      </li>
      <li class="<%= active_sidebar_active?(:wishlists, :all) %>">
        <%= link_to userpage_wishlists_path do %>
          <i class="fa fa-heart"></i>
          &nbsp;&nbsp;Wishlists
          <span class="pull-right">
            <span class="badge"><%= @wishlists_size %></span>
          </span>
        <% end %>
      </li>
      <li class="<%= active_sidebar_active?(:inquiries, :all) %>">
        <%= link_to userpage_inquiries_path do %>
          <i class="fa fa-comments"></i>
          &nbsp;&nbsp;Inquiries
          <span class="pull-right">
            <span class="badge"><%= @inquiries_size %></span>
          </span>
        <% end %>
      </li>
      <li class="<%= active_sidebar_active?(:properties, :all) %>">
        <%= link_to userpage_properties_path do %>
          <i class="fa fa-flag"></i>
          &nbsp;&nbsp;Advertisements
          <span class="pull-right">
            <span class="badge"><%= @properties_size %></span>
          </span>
        <% end %>
      </li>
      <li class="<%= active_sidebar_active?(:sold_reports, :all) %>">
        <%= link_to userpage_sold_reports_path do %>
          <i class="fa fa-file-text"></i>
          &nbsp;&nbsp;Sales Reports
          <span class="pull-right">
            <span class="badge"><%= @reports_size %></span>
          </span>
        <% end %>
      </li>
      <li class="<%= active_sidebar_active?(:packages, :all) %>">
        <%= link_to userpage_packages_path do %>
          <i class="fa fa-file-text"></i>
          &nbsp;&nbsp;Package
          <span class="pull-right">
            <span class="badge"><%#= @reports_size %></span>
          </span>
        <% end %>
      </li>
      <li>
        <hr>
      </li>
      <li class="<%= active_sidebar_active?(:members, :all) ||  active_sidebar_active?(:agents, :all) %>">
        <%= link_to user_edit_url(current_user.type, current_user) do %>
          <i class="fa fa-wrench"></i>
          &nbsp;&nbsp;Edit Profile
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: 'delete' do %>
          <i class="fa fa-mail-reply"></i>
          &nbsp;&nbsp;SignOut
        <% end %>
      </li>
    </ul>
  </nav>
</div>

app/views/shareds/users/_sidebar_right.html.erb
<div class="nav-sidebar-users-right">
  <div class="sidebar-users-right-wrapper">
    <div class="title">
      Do you want to become an agent?
    </div>
    <div class="description">
      Your member account can be upgraded to become an agent account, with the features of the service agent that you get on this website more numerous and diverse, by clicking the link below:
    </div>
    <div class="image-icon">
      <div class="row">
        <div class="col-md-12">
          <%= link_to upgrade_userpage_member_path(current_user), method: 'put' do %>
            <%= current_user.agent_processed? %>
          <% end %>
        </div>
        <div class="break"></div>
        <div class="col-md-12">
          <strong>Member Since : </strong><br>
          <%= current_user.try(:created_at).strftime("%H:%M %B, %d, %Y") if current_user.try(:created_at).present? %>
          <br><br>
          <strong>Last Sign in : </strong><br>
          <%= current_user.try(:last_sign_in_at).strftime("%H:%M %B, %d, %Y") if current_user.try(:last_sign_in_at).present? %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- upgrade_userpage_member_path(current_user) -->