config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root 'publics#home'

  resources :properties do
    collection do
      get :auction
      get :featureds, to: 'properties#featured'
      get 'wishlist/:id', to: 'properties#wishlist', as: 'wishlist'
      post :checkout_bid
    end
  end

  resources :projects do
    collection { get :featureds, to: 'projects#featureds' }
  end
  resources :users, only: [:show] do
    member do
      get :about_company
      get 'reviews', to: 'users#reviews'
      delete 'reviews/:rate_id', to: 'users#delete_reviews', as: 'delete_rate'
      post 'reviews', to: 'reviews#create'
    end
  end
  resources :landing_pages, only: [:show]
  resources :inquiries
  resources :feedbacks, only: [:create]
  resources :reports, only: [:create]
  resources :schedule_visits, only: [:create]

  get 'map',                          to: 'properties#map',             as: 'map'
  get 'list',                         to: 'properties#list',            as: 'list'
  get 'package',                      to: 'publics#package',            as: 'package'
  get 'get_societies',                to: 'publics#get_societies',      as: 'get_societies'

  get 'get_assets',                   to: 'xhrs#get_assets',            as: 'get_assets'
  get 'get_assets_property',          to: 'xhrs#get_assets_property',   as: 'get_assets_property'
  post 'save_assets_property',        to: 'xhrs#save_assets_property',  as: 'save_assets_property'
  get 'get_project_assets',           to: 'xhrs#get_project_assets',    as: 'get_project_assets'
  get 'get_assets_project',           to: 'xhrs#get_assets_projects',   as: 'get_assets_project'
  post 'save_assets_project',         to: 'xhrs#save_assets_project',   as: 'save_assets_project'
  get 'get_categories',               to: 'publics#get_categories',     as: 'get_categories'
  get 'cities_tag',                   to: 'publics#cities_tag',         as: 'cities_tag'
  get 'cities',                       to: 'xhrs#cities',                as: 'cities'
  get 'subdistricts',                 to: 'xhrs#subdistricts',          as: 'subdistricts'
  get 'village',                      to: 'xhrs#village',               as: 'village'
  get 'area',                         to: 'xhrs#area',                  as: 'area'
  get 'get_by_city',                  to: 'xhrs#get_by_city',           as: 'get_by_city'
  get 'get_properties_search',        to: 'xhrs#get_properties_search', as: 'get_properties_search'
  get '/get_detail_profile_property', to: 'xhrs#get_detail_properties', as: 'get_detail_profile_property'
  get '/get_detail_profile_project',  to: 'xhrs#get_detail_projects',   as: 'get_detail_profile_project'
  get '/label_packages',              to: 'xhrs#label_packages',        as: 'label_packages'

  get "autocomplete_region", to: "xhrs#autocomplete_region"
  get "autocomplete_auction_region", to: "xhrs#autocomplete_auction_region"

  resources :xhrs do
    collection do
      get :get_categories
      get :get_facilities
    end
  end

  namespace :backend do
    # The Role
    resources :roles, except: :show do
      patch 'change', on: :member
      resources :sections, controller: 'role_sections', only: :none do
        collection do
          post :create
          post :create_rule
          post :create_field

        end

        member do
          put :rule_on
          put :rule_off

          delete :destroy
          delete :destroy_rule
        end
      end
    end

    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :admins
    resources :members do
      collection do
        post :do_multiple_act
      end
    end
    resources :agents do
      collection do
        post :do_multiple_act
      end
    end
    resources :packages do
      collection do
        post :do_multiple_act
      end
    end
    resources :order_user_packages do
      member do
        patch '/confirmations', to: 'order_user_packages#confirmations'
      end
      collection do
        post '/multiple_confirmations', to: 'order_user_packages#multiple_confirmations'
      end
    end
    resources :developers do
      collection do
        post :do_multiple_act
      end
    end
    resources :properties do
      collection do
        post :do_multiple_act
        get :import, to: 'properties#import'
        post :do_import, to: 'properties#do_import'
        post :import, to: 'properties#do_import'
      end
    end
    resources :auction_properties do
      collection do
        post :do_multiple_act
      end
    end
    resources :property_types do
      collection do
        post :do_multiple_act
      end
    end
    resources :asset_facilities do
      collection do
        post :do_multiple_act
      end
    end
    resources :projects do
      collection do
        post :do_multiple_act
        get :import, to: 'projects#import'
        post :do_import, to: 'projects#do_import'
        post :import, to: 'projects#do_import'
      end
    end
    resources :locations do
      collection do
        post :do_multiple_act
      end
    end
    resources :supporteds do
      collection do
        post :do_multiple_act
      end
    end
    resources :testimonials do
      collection do
        post :do_multiple_act
      end
    end
    resources :feedbacks do
      collection do
        post :do_multiple_act
      end
    end
    resources :reports do
      collection do
        post :do_multiple_act
      end
    end
    resources :sold_reports do
      collection do
        post :do_multiple_act
      end
    end
    resources :regions
    resources :landing_pages
    resources :web_settings
  end

  namespace :userpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members do
      member do
        put :upgrade
      end
    end
    resources :agents, only: [:edit, :update, :show]
    resources :wishlists
    resources :inquiries
    resources :notifications
    resources :properties do
      member do
        put :renew
      end
      collection do
        post :do_report_sold
      end
    end
    resources :sold_reports
    resources :packages do
      collection do
        get :invoices
      end
      member do
        get :invoice
      end
    end
  end

  namespace :developerpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :developers, only: [:edit, :update, :show]
    resources :wishlists
    resources :inquiries
    resources :notifications
    resources :projects
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
	extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  include ScopeBased
  include TheProject::ProjectConfig
  include TheProject::ProjectSearching

  validates_uniqueness_of :code, if: 'self.code.present?'

  PRICE_LIST=[50000000, 100000000, 200000000, 500000000, 1000000000, 2000000000, 5000000000, 10000000000, 20000000000]
  PRICEMETER_LIST=[100000, 250000, 500000, 750000, 1000000, 1500000, 2000000, 5000000, 7500000]

  def status_area?
    if self.type_project == 'Apartment' || self.type_project == 'Office Tower'
      return 'Gross Area in m<sup>2</sup>'.html_safe
    else
      return 'Area m<sup>2</sup>'.html_safe
    end
  end

  def status_price?
    if self.type_project == 'House'
      return 'Starting Price'
    else
      return ''
    end
  end

  def latitude
    address.latitude
  end

  def longitude
    address.longitude
  end

  def price_for_meter
    if self.type_project != 'House'
      self.price_in_meter
    else
      ""
    end
  end

end

app/controllers/backend/projects_controller.rb
class Backend::ProjectsController < Backend::ApplicationController
  include ActionView::Helpers::NumberHelper
	defaults resource_class: Project, collection_name: 'projects', instance_name: 'project'
  before_action :role_required

	add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Projects", :collection_path

  before_filter :prepare_map_location, except: [:index, :destroy]
  before_filter :prepare_user
  before_filter :prepare_types
  before_filter :prepare_facilities_edit, only: [:edit, :update]
  before_filter :prepare_facilities_new, only: [:new]

  include MultipleAction

	def index
    if 1 === params[:export].to_i
      params[:per_page] = -1
      params[:bonds] = 'export'
      collection_data = Project.search_by(params)
      cols = export(collection_data)
      respond_to do |format|
        format.xls { send_data cols,filename: "data_projects_#{Time.now.to_i}.xls" }
      end
    else
  		@collection = collection.latest.page(page).per(per_page)
    end
	end

	def create
		build_resource
    resource.facilities = params[:facilities]
		create! do |format|
      if resource.errors.empty?
        format.html {redirect_to collection_path}
      else
        flash[:errors] = resource.errors.full_messages
        format.html {redirect_to :back}
      end
    end
	end

	def update
    resource.facilities = params[:facilities]
		update! do |format|
      if resource.errors.empty?
        format.html {redirect_to collection_path}
      else
        flash[:errors] = resource.errors.full_messages
        format.html {redirect_to :back}
      end
    end
	end

  def import
  end

  def do_import
    if params[:file].present?
      options = {file: params[:file]}
      options.merge!(params.slice(:start_row, :columns).deep_symbolize_keys)
      ImportWorker.perform_by_env(ImportModel::Project.name, options)
      flash[:notice] = 'Your import is enqueued, Your Import Data Will Execute later'
    end
    redirect_to backend_projects_path
  end

	protected
		def collection
			@collection ||= end_of_association_chain.search_by(params)
		end

    def prepare_types
      @types = PropertyType.find_by(name: 'New Project').children.pluck(:name)
    end

		def prepare_user
			@users = Developer.alfa.pluck(:username, :id)
		end

		def prepare_map_location
			if params[:action] == "edit" || params[:action] == "update"
         city = resource.address.city
         @others = Project.joins(:address).where("projects.id != ?", resource.id).filter_by_city(city).check_latlang.map{|l| [l.title, l.address.latitude, l.address.longitude, l.price.to_i, l.type_project, l.first_image(:small), number_to_currency_br(l.price_in_meter)]}
       else
         @others = []
       end
		end

    def number_to_currency_br(number)
      number = 0 if number.blank?
      number_to_currency(number, :unit => "Rp ", :separator => ",", :delimiter => ".", precision: 0)
    end

    def prepare_facilities_edit
      @facilities = AssetFacility.latest.where("LOWER(category) LIKE LOWER('%#{resource.type_project}%')")
    end

    def prepare_facilities_new
      @facilities = AssetFacility.latest
    end
end

app/controllers/developerpage/projects_controller.rb
class Developerpage::ProjectsController < Developerpage::ApplicationController
  include ActionView::Helpers::NumberHelper
	defaults resource_class: Project, collection_name: 'projects', instance_name: 'project'
  load_and_authorize_resource

	add_breadcrumb "Dashboard", :developerpage_dashboard_path
  add_breadcrumb "Projects", :collection_path

  before_filter :prepare_map_location, except: [:index, :destroy]
  before_filter :prepare_types
  before_filter :prepare_facilities_edit, only: [:edit, :update]
  before_filter :prepare_facilities_new, only: [:new]

	def index
		@projects = current_user.projects.latest
		@collection = @projects.page(page).per(per_page)
	end

	def create
		build_resource
		resource.user_id = current_user.id
    resource.facilities = params[:facilities]
		create! do |format|
      if resource.errors.empty?
        UserMailer.send_request_project(resource).deliver
        format.html {redirect_to collection_path}
      else
        format.html {redirect_to :back, errors: resource.errors.full_messages}
      end
    end
	end

	def update
    resource.facilities = params[:facilities]
		update! do |format|
      if resource.errors.empty?
        format.html {redirect_to collection_path}
      else
        format.html {redirect_to :back, errors: resource.errors.full_messages}
      end
    end
	end

	protected
		def collection
			@collection ||= end_of_association_chain
		end

		def prepare_map_location
      if params[:action] == "edit" || params[:action] == "update"
        village_id = resource.address.village_id
        @others = Project.joins(:address).where("projects.id != ?", resource.id).filter_by_village_id(village_id).check_latlang.map{|l| [l.title, l.address.latitude, l.address.longitude, l.price.to_i, l.type_project, l.first_image(:small), number_to_currency_br(l.price_in_meter)]}
      else
        @others = []
      end
		end

    def number_to_currency_br(number)
      number = 0 if number.blank?
      number_to_currency(number, :unit => "Rp ", :separator => ",", :delimiter => ".", precision: 0)
    end

    def prepare_types
      @types = PropertyType.find_by(name: 'New Project').children.pluck(:name)
    end

		def prepare_facilities_edit
      @facilities = AssetFacility.latest.where("LOWER(category) LIKE LOWER('%#{resource.type_project}%')")
    end

    def prepare_facilities_new
      @facilities = AssetFacility.latest
    end
end

app/controllers/projects_controller.rb
class ProjectsController < FrontendController
  impressionist actions: [:show]
	before_filter :prepare_map_types

	layout 'application_projects_map'

	def index
    if params[:search].present?
      prepare_facilities_search(params[:type_project]) if params[:type_project].present?
    end

		if params[:list].present?
      search = params[:region_display_name].split(',').first if params[:region_display_name]
      reg = search.present? ? search : params[:city].present? ? params[:city] : params[:province].present? ? params[:province] : "Kota Jakarta Pusat"
      params[:city] = params[:city].present? ? params[:city] : "Kota Jakarta Pusat" if params[:region_display_name].blank?
      @region = Region.where(name: reg).first
			@list_projects = Project.search_by(params).latest.activated
			render :map
		else
			projects = collection

      @projects_count = projects.size
			@projects = projects.page(page).per(per_page)
			@featureds = projects.featured.limit(5)
      respond_to do |format|
        format.html { render :list }
        format.js { render 'index.js'}
      end
		end
	end

	def show
		@project = Project.find(params[:id])
    impressionist(@project, 'message')
		@inquiry = Inquiry.new
    @facilities = AssetFacility.latest.where("LOWER(category) LIKE LOWER('%#{@project.type_project}%')")
	end

  def featureds
    @featureds = Project.activated.featured.page(page).per(per_page)
    @latest_projects = Project.activated.latest.limit(10)
  end

	private
		def prepare_map_types
      @types_location = LocationType.to_a
			@types = PropertyType.find_by(name: 'New Project').children.map(&:name)
      @others = []
      # city = params[:city].present? ? params[:city] : "Aceh Barat"
      # @projects = Project.joins(:address).filter_by_city(city).check_latlang.map{|l| [l.id, l.title, l.address.latitude, l.address.longitude, l.price.to_i]}
		end

    def collection
      @collection ||= Project.search_by(params).latest.activated.page(page).per(per_page)
    end

    def prepare_facilities_search(type)
      @facility_list = AssetFacility.latest.where("LOWER(category) LIKE LOWER('%#{type}%')")
    end

end

app/views/shareds/projects/_basic_builder.html.erb
<% user = resource.try(:user) %>
<% profile = user.try(:profile) %>
<% contact = user.try(:contact) %>
<section class="section section-desc-white" id="section-builder">
	<div class="row">
		<div class="col-md-12">
			<div class="user-image-cycle float-none margin-none">
				<%= image_tag "#{profile.try(:avatar).url(:small)}", class: 'host-profile-image' %>
			</div>
		</div>
		<div class="col-md-12">
			<h4 align="center">
				<%= profile.try(:full_name) %>
			</h4>
			<center>
				<div class="text-muted color-blue small">
		      <%= user.verified? %>
		    </div>
				<div class="text-muted small">
					The Builder
				</div>
			</center>
			<div class="break"></div>
			<div class="builder-details row">
	      <div class="col-xs-6">
	        <div class="text-uppercase">Established in </div>
	        <div class="value"><%= profile.try(:birthday).strftime("%B, %Y") if profile.birthday.present? %></div>
	      </div>
	      <div class="col-xs-6">
	        <div class="text-uppercase">Total Projects</div>
	        <div class="value"><%= user.try(:projects).try(:count) %></div>
	      </div>
	    </div>
	    <div class="break"></div>
			<p><%= profile.try(:meta_description).html_safe if profile.meta_description.present? %></p>
		</div>
	</div>
</section>

app/views/shareds/projects/_basics.html.erb
<section class="section-desc">
	<h2 class="heading text-uppercase">Overview</h2>
	<div class="body-cont">
		<section class="utilities">
			<span class="entity">
				<span class="entity-left">
					<i class="fa fa-bookmark"></i>
				</span>
				<span class="entity-right">
					<span class="text">Construction</span>
					<br>
					<span class="value">
						<span><%= resource.construction %></span>
					</span>
				</span>
			</span>
			<span class="entity">
				<span class="entity-left">
					<i class="fa fa-tags"></i>
				</span>
				<span class="entity-right">
					<span class="text">Base Price</span>
					<br>
					<span class="value">
						<span><%= number_to_currency_br(resource.price) %></span>
					</span>
				</span>
			</span>
			<span class="entity">
				<span class="entity-left">
					<i class="fa fa-building"></i>
				</span>
				<span class="entity-right">
					<span class="text">Project Size</span>
					<br>
					<span class="value">
						<span><%= resource.project_size %> Buildings</span>
					</span>
				</span>
			</span>
			<span class="entity">
				<span class="entity-left">
					<i class="fa fa-calendar"></i>
				</span>
				<span class="entity-right">
					<span class="text">Possession Starts</span>
					<br>
					<span class="value">
						<span><%= resource.try(:possession_start).strftime("%B, %d, %Y") %></span>
					</span>
				</span>
			</span>
			<span class="entity">
				<span class="entity-left">
					<i class="fa fa-home"></i>
				</span>
				<span class="entity-right">
					<span class="text">Configurations</span>
					<br>
					<span class="value">
						<span>
							<%= resource.overviews.pluck(:title).to_sentence %>
						</span>
					</span>
				</span>
			</span>
		</section>
	</div>
</section>

app/views/shareds/projects/_builder.html.erb
<% user = resource.try(:user) %>
<% profile = user.try(:profile) %>
<% contact = user.try(:contact) %>
<div class="line-through" id="section-builder">
	<p><span class="grey">Builder</span></p>
</div>
<div class="break"></div>
<section class="section section-desc-white">
	<div class="row">
		<div class="col-md-2">
			<div class="img-builder-center-show">
				<div class="user-image-cycle float-none margin-none">
					<%= image_tag "#{profile.try(:avatar).url(:small)}", class: 'host-profile-image' %>
				</div>
			</div>
		</div>
		<div class="col-md-10">
			<div class="name-builder-center-show">
				<h4><%= profile.try(:full_name) %></h4>
				<div class="builder-details row">
		      <div class="col-md-5 col-sm-5 col-xs-5">
		        <div class="text-uppercase">Established in </div>
		        <div class="value"><%= profile.try(:birthday).strftime("%B, %Y") if profile.birthday.present? %></div>
		      </div>
		      <div class="col-md-7 col-sm-7 col-xs-7">
		        <div class="text-uppercase">Total Projects</div>
		        <div class="value"><%= user.try(:projects).try(:count) %></div>
		      </div>
		    </div>
		    <div class="break"></div>
				<p><%= profile.try(:meta_description).html_safe if profile.meta_description.present? %></p>
			</div>
		</div>
	</div>
</section>

app/views/shareds/projects/_facilities.html.erb
<% facilities = resource.try(:facilities) %>
<% if facilities.present? %>
	<section class="utilities">
		<h2 class="heading text-uppercase">Facilities</h2>
		<% @facilities.each do |s| %>
			<% if facilities.include?(s.name) %>
				<span class="entity">
					<span class="entity-left">
						<%= s.font_icon.html_safe if s.font_icon.present? %>
					</span>
					<span class="entity-right">
						<span class="text"><%= s.name %></span>
						<br>
						<span class="value">
							<span>
								<% if facilities.include?(s.name) %>
									<%= 'Available' %>
								<% else %>
									<%= 'Not Available' %>
								<% end %>
							</span>
						</span>
					</span>
				</span>
			<% end %>
		<% end %>
	</section>
<% end %>

app/views/shareds/projects/_side_right.html.erb
<% user = resource.try(:user) %>
<% profile = user.try(:profile) %>
<% contact = user.try(:contact) %>
<div class="col-md-4 contact-user-to-fixed">
	<center class="contact-user-font-section">
		<% if user %>
			<div class="line-through">
				<p><span>Contact Builder</span></p>
			</div>
			<div class="col-md-12">
				<%= link_to user_path(user) do %>
					<div class="user-image-cycle float-none margin-none">
						<%= image_tag "#{profile.try(:avatar).url(:small)}", class: 'host-profile-image' %>
					</div>
				<% end %>
			</div>
			<div class="break"></div>
			<%= link_to user_path(user) do %>
				<h4><%= profile.try(:full_name) %></h4>
			<% end %>
			<div class="text-muted small">
				<%= user.try(:type) %>
			</div>
			<span class="uppercase">
	      ID <%= user.try(:code) %>
	    </span>
	    <div class="phone">
	      <i class="fa fa-mobile"></i> <%= contact.try(:handphone) %>
	    </div>
	    <div class="text-muted color-blue small">
	      <%= user.verified? %>
	    </div>
			<div class="text-muted small">
				Since <%= resource.try(:created_at).strftime("%B, %d, %Y") %>
			</div>
			<br>
			<div class="line-through"></div>
			<div class="bottom">
				<%= form_for @inquiry, url: inquiries_path, method: 'post' do |f| %>
					<%= f.hidden_field :inquiriable_id, value: resource.id %>
					<%= f.hidden_field :inquiriable_type, value: resource.class %>
					<%= f.hidden_field :owner_id, value: resource.try(:user).try(:id) %>
					<%= render 'shareds/messages/form', f: f %>
				<% end %>
			</div>
		<% end %>
	</center>
	<div class="col-md-12 padding0">
		<div class="btn-group grid-controls-action-show-property">
			<button class="btn btn-default click-block-share-social">
				<i class="fa fa-share-alt"></i> Share
			</button>
			<button class="btn btn-default" data-toggle='modal' data-target="#modal-report">
				<i class="fa fa-flag-o"></i> Report
			</button>
		</div>
		<div class="block-share-social">
			<span class='st_sharethis_large' displayText='ShareThis'></span>
			<span class='st_facebook_large' displayText='Facebook'></span>
			<span class='st_twitter_large' displayText='Tweet'></span>
			<span class='st_pinterest_large' displayText='Pinterest'></span>
			<span class='st_email_large' displayText='Email'></span>
		</div>
	</div>
</div>

<%= render 'shareds/modal_report', resource: resource %>

app/views/shareds/projects/_sidebar_right_fitured.html.erb
<%= link_to featureds_projects_path do %>
  <div class="top-label-side-fitured">
    <span class="fa fa-list-alt"></span>
    &nbsp;&nbsp;List Featured Projects
  </div>
<% end %>

<% @featureds.each do |resource| %>
  <% user = resource.try(:user) %>
  <% profile = user.try(:profile) %>
  <% address = resource.try(:address) %>
  <% cache ["properties_featured_side_#{resource.id}_#{resource.updated_at.to_time.to_i}"] do %>
    <div class="col-lg-12 col-md-12 col-sm-6 col-xs-12">
      <div class="row">
        <div class="side-right-fitured">
          <div class="col-md-12">
            <div class="row">
              <div id="project-caousel-<%= resource.id %>" class="project-carousel-side carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <% resource.try(:galleries).each_with_index do |resource, index| %>
                    <div class="item <%= 'active' if index == 0 %>">
                      <%= image_tag resource.try(:file).url(:large) %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#project-caousel-<%= resource.id %>" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#project-caousel-<%= resource.id %>" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="row">
              <div class="box-info-featured-wrapper">
                <div class="title">
                  <%= link_to resource.title, project_path(resource) %>
                </div>
                <hr class="hr-small">
                <div class="row">
                  <div class="col-xs-9">
                    <span class="price">
                      <%= number_to_currency_br(resource.price) if resource.price.present? %>
                    </span>
                    <small class='color-grey'><%= resource.status_price? %></small>
                    <% unless resource.type_project == 'House' %>
                      |
                      <span class="price-sq">
                        <%= raw "#{number_to_currency_br(resource.price_in_meter)} <small class='color-grey'> per sq m</small>" %>
                      </span>
                    <% end %>
                  </div>
                  <div class="col-xs-3 padding-left0">
                    <div class="pull-right color-green">
                      <small class="box-sub-info">
                        <span class="fa fa-area-chart"></span>
                        <span class="name"><%= resource.try(:construction) %></span>
                      </small>
                    </div>
                  </div>
                </div>
                <div class="more-info">
                  <div>
                    <span class="label-info">Flat Id : </span> <span class="uppercase"><%= resource.try(:code) %></span>
                  </div>
                  <div>
                    <span class="label-info">Property : </span> <span><%= resource.try(:type_project) %></span> &nbsp;
                    <span class="label-info">Project Size : </span> 
                    <span><%= resource.try(:project_size).to_s + ' Buildings' if resource.project_size.present? %></span>
                  </div>
                  <div>
                    <span class="label-info">Configurations : </span> <span><%= resource.overviews.pluck(:title).to_sentence %></span>
                  </div>
                </div>
                <div class="box-location">
                  <div class="box-sub-info">
                    <span class="fa fa-map-marker"></span>
                    <span class="name">
                      <%= address.try(:city) %>
                    </span>
                  </div>
                </div>
                <%= link_to user_path(user), class: "full-width btn btn-outlined btn-red-light btn-sm" do %>
                  <i class="fa fa-user"></i>
                  <%= profile.full_name %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shareds/projects/_sort_order.html.erb
<div class="col-md-12">
	<div class="pull-left">
		<div class="btn-group">
			<button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
				<span class="glyphicon glyphicon-sort-by-attributes"></span> Sort By &nbsp; &nbsp;<span class="caret"></span>
			</button>
			<ul class="dropdown-menu" role="menu" id="sort_order_project">
				<li><a href="#">Newest</a></li>
				<li><a href="#">Oldest</a></li>
				<li><a href="#">Price (Low to High)</a></li>
				<li><a href="#">Price (High to Low)</a></li>
			</ul>
		</div>
	</div>
	<div class="pull-right">
		<div class="btn-group grid-controls">
			<% params.delete(:page) %>
			<% params.delete(:per_page) %>
			<%= link_to projects_path({list: 'map'}.merge(params)), class: "btn btn-default" do %>
			<i class="fa fa-map-marker"></i> Map
			<% end %>
			<%= link_to "javascript:void(0)", class: "btn btn-default #{'active' unless params[:list].present?}" do %>
			<i class="fa fa-navicon"></i> List
			<% end %>
		</div>
	</div>
</div>
<br>

app/views/shareds/projects/_sort_order_map.html.erb
<div class="margin-top10">
	<div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
		<div class="results">
			<i class="fa fa-list"></i> <b><%= @list_projects.count %></b> Results Founds
		</div>
	</div>
	<div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 padding-right0">
		<div class="btn-group grid-controls pull-right">
			<% new_params = params.dup %>
			<% new_params.delete(:controller) %>
			<% new_params.delete(:action) %>
			<% new_params.delete(:page) %>
			<% new_params.delete(:per_page) %>
			<% new_params.delete(:list) %>
			<%= link_to "javascript:void(0)", class: "btn btn-default #{'active' if params[:list].present?}" do %>
				<i class="fa fa-map-marker"></i> Map
			<% end %>
			<%= link_to projects_path(new_params), class: "btn btn-default" do %>
				<i class="fa fa-navicon"></i> List
			<% end %>
		</div>
	</div>
</div>
<div class="col-md-12 padding-right0">
	<div class="input-group">
		<span class="input-group-addon">Sort By</span>
		<select name="sort" class="form-control" id="sort_order_project">
			<option <%= 'selected=selected' if params[:sort] == 'Newest' %>><a href="javasript:void(0)">Newest</a></option>
			<option <%= 'selected=selected' if params[:sort] == 'Oldest' %>><a href="javasript:void(0)">Oldest</a></option>
			<option <%= 'selected=selected' if params[:sort] == 'Price (Low to High)' %>><a href="javasript:void(0)">Price (Low to High)</a></option>
			<option <%= 'selected=selected' if params[:sort] == 'Price (High to Low)' %>><a href="javasript:void(0)">Price (High to Low)</a></option>
		</select>
	</div>
	<div class="line-through">
		<p><span><%= @region.name rescue "CENTRAL JAKARTA" %> Project</span></p>
	</div>
</div>