config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root 'publics#home'

  resources :properties do
    collection do
      get :auction
      get :featureds, to: 'properties#featured'
      get 'wishlist/:id', to: 'properties#wishlist', as: 'wishlist'
      post :checkout_bid
    end
  end

  resources :projects do
    collection { get :featureds, to: 'projects#featureds' }
  end
  resources :users, only: [:show] do
    member do
      get :about_company
      get 'reviews', to: 'users#reviews'
      delete 'reviews/:rate_id', to: 'users#delete_reviews', as: 'delete_rate'
      post 'reviews', to: 'reviews#create'
    end
  end
  resources :landing_pages, only: [:show]
  resources :inquiries
  resources :feedbacks, only: [:create]
  resources :reports, only: [:create]
  resources :schedule_visits, only: [:create]

  get 'map',                          to: 'properties#map',             as: 'map'
  get 'list',                         to: 'properties#list',            as: 'list'
  get 'package',                      to: 'publics#package',            as: 'package'
  get 'get_societies',                to: 'publics#get_societies',      as: 'get_societies'

  get 'get_assets',                   to: 'xhrs#get_assets',            as: 'get_assets'
  get 'get_assets_property',          to: 'xhrs#get_assets_property',   as: 'get_assets_property'
  post 'save_assets_property',        to: 'xhrs#save_assets_property',  as: 'save_assets_property'
  get 'get_project_assets',           to: 'xhrs#get_project_assets',    as: 'get_project_assets'
  get 'get_assets_project',           to: 'xhrs#get_assets_projects',   as: 'get_assets_project'
  post 'save_assets_project',         to: 'xhrs#save_assets_project',   as: 'save_assets_project'
  get 'get_categories',               to: 'publics#get_categories',     as: 'get_categories'
  get 'cities_tag',                   to: 'publics#cities_tag',         as: 'cities_tag'
  get 'cities',                       to: 'xhrs#cities',                as: 'cities'
  get 'subdistricts',                 to: 'xhrs#subdistricts',          as: 'subdistricts'
  get 'village',                      to: 'xhrs#village',               as: 'village'
  get 'area',                         to: 'xhrs#area',                  as: 'area'
  get 'get_by_city',                  to: 'xhrs#get_by_city',           as: 'get_by_city'
  get 'get_properties_search',        to: 'xhrs#get_properties_search', as: 'get_properties_search'
  get '/get_detail_profile_property', to: 'xhrs#get_detail_properties', as: 'get_detail_profile_property'
  get '/get_detail_profile_project',  to: 'xhrs#get_detail_projects',   as: 'get_detail_profile_project'
  get '/label_packages',              to: 'xhrs#label_packages',        as: 'label_packages'

  get "autocomplete_region", to: "xhrs#autocomplete_region"
  get "autocomplete_auction_region", to: "xhrs#autocomplete_auction_region"

  resources :xhrs do
    collection do
      get :get_categories
      get :get_facilities
    end
  end

  namespace :backend do
    # The Role
    resources :roles, except: :show do
      patch 'change', on: :member
      resources :sections, controller: 'role_sections', only: :none do
        collection do
          post :create
          post :create_rule
          post :create_field

        end

        member do
          put :rule_on
          put :rule_off

          delete :destroy
          delete :destroy_rule
        end
      end
    end

    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :admins
    resources :members do
      collection do
        post :do_multiple_act
      end
    end
    resources :agents do
      collection do
        post :do_multiple_act
      end
    end
    resources :packages do
      collection do
        post :do_multiple_act
      end
    end
    resources :order_user_packages do
      member do
        patch '/confirmations', to: 'order_user_packages#confirmations'
      end
      collection do
        post '/multiple_confirmations', to: 'order_user_packages#multiple_confirmations'
      end
    end
    resources :developers do
      collection do
        post :do_multiple_act
      end
    end
    resources :properties do
      collection do
        post :do_multiple_act
        get :import, to: 'properties#import'
        post :do_import, to: 'properties#do_import'
        post :import, to: 'properties#do_import'
      end
    end
    resources :auction_properties do
      collection do
        post :do_multiple_act
      end
    end
    resources :property_types do
      collection do
        post :do_multiple_act
      end
    end
    resources :asset_facilities do
      collection do
        post :do_multiple_act
      end
    end
    resources :projects do
      collection do
        post :do_multiple_act
        get :import, to: 'projects#import'
        post :do_import, to: 'projects#do_import'
        post :import, to: 'projects#do_import'
      end
    end
    resources :locations do
      collection do
        post :do_multiple_act
      end
    end
    resources :supporteds do
      collection do
        post :do_multiple_act
      end
    end
    resources :testimonials do
      collection do
        post :do_multiple_act
      end
    end
    resources :feedbacks do
      collection do
        post :do_multiple_act
      end
    end
    resources :reports do
      collection do
        post :do_multiple_act
      end
    end
    resources :sold_reports do
      collection do
        post :do_multiple_act
      end
    end
    resources :regions
    resources :landing_pages
    resources :web_settings
  end

  namespace :userpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members do
      member do
        put :upgrade
      end
    end
    resources :agents, only: [:edit, :update, :show]
    resources :wishlists
    resources :inquiries
    resources :notifications
    resources :properties do
      member do
        put :renew
      end
      collection do
        post :do_report_sold
      end
    end
    resources :sold_reports
    resources :packages do
      collection do
        get :invoices
      end
      member do
        get :invoice
      end
    end
  end

  namespace :developerpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :developers, only: [:edit, :update, :show]
    resources :wishlists
    resources :inquiries
    resources :notifications
    resources :projects
  end
end

app/models/auction_property.rb
class AuctionProperty < Property
	extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  after_initialize :after_initialized
	default_scope {where(category: 'Auction Property')}

	private
		def after_initialized
			self.address ||= Address.new if self.new_record?
			self.basic_property ||= BasicProperty.new if self.new_record?
			self.auction ||= Auction.new if self.new_record?
		end
end

app/controllers/backend/admins_controller.rb
class Backend::AdminsController < Backend::ApplicationController
	defaults resource_class: Admin, collection_name: 'admins', instance_name: 'admin'
  before_action :role_required

	add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Admins"

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def update
  	update! do |format|
  		if resource.errors.empty?
        format.html { redirect_to :back}
      else
        flash[:errors] = resource.errors.full_messages
        format.html { redirect_to :back}
      end
  	end
  end
end

app/controllers/backend/agents_controller.rb
class Backend::AgentsController < Backend::ApplicationController
	defaults resource_class: Agent, collection_name: 'agents', instance_name: 'agent'
  before_action :role_required

	add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Agents", :collection_path

  include MultipleAction

	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	protected
		def collection
			@collection ||= end_of_association_chain.search_by(params)
		end
end

app/controllers/backend/application_controller.rb
class Backend::ApplicationController < Backend::ResourcesController
	include TheRole::Controller
  layout 'backend'

	before_filter :authenticate_admin!, :prepare_count
	protect_from_forgery with: :exception

	def authenticate_admin!
  	unless current_user.present? && (current_user.is_admin?)
      redirect_to root_path, alert: "Can't Access this page"
    end
  end

  protected
    def prepare_count
      @members_size = Member.all.size
      @agents_size = Agent.all.size
      @developers_size = Developer.all.size
      @properties_size = Property.all.size
      @projects_size = Project.all.size
      @balance_order_user_package = UserPackage.payed.where.not(price: nil).pluck(:price)
    end

    def per_page
      params[:per_page] ||= 20
    end

    def page
      params[:page] ||= 1
    end
end

app/controllers/backend/asset_facilities_controller.rb
class Backend::AssetFacilitiesController < Backend::ApplicationController
	defaults resource_class: AssetFacility, collection_name: 'asset_facilities', instance_name: 'asset_facility'
  before_action :role_required

	add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Asset Facilities", :collection_path

  before_filter :prepare_categories

  include MultipleAction

	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	def create
		build_resource
		resource.category = params[:categories]
		create! do |format|
      if resource.errors.empty?
        format.html {redirect_to collection_path}
      else
        flash[:errors] = resource.errors.full_messages
        format.html {redirect_to :back}
      end
    end
	end

	def update
		resource.category = params[:categories]
		update! do |format|
      if resource.errors.empty?
        format.html {redirect_to collection_path}
      else
        flash[:errors] = resource.errors.full_messages
        format.html {redirect_to :back}
      end
    end
	end

	protected
		def collection
			@collection ||= end_of_association_chain
		end

		def prepare_categories
			@categories = ['House', 'Apartment','Ruko','Factory','Land','Office','Warehouse','Commercial Business - Business Unit']
		end
end

app/controllers/backend/auction_properties_controller.rb
class Backend::AuctionPropertiesController < Backend::ApplicationController
  include ActionView::Helpers::NumberHelper
  defaults resource_class: AuctionProperty, collection_name: 'auction_properties', instance_name: 'auction_property'
  before_action :role_required

	add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Auction Properties", :collection_path

  before_filter :prepare_map_location, except: [:index, :destroy]
  before_filter :prepare_user
  before_filter :prepare_types
  before_filter :prepare_facilities_edit, only: [:edit, :update]
  before_filter :prepare_facilities_new, only: [:new]

  include MultipleAction

	def index
		@collection = collection
	end

	def create
		build_resource
    resource.facilities = params[:facilities]
		create! do |format|
      if resource.errors.empty?
        format.html {redirect_to collection_path}
      else
        flash[:errors] = resource.errors.full_messages
        format.html {redirect_to :back}
      end
    end
	end

	def update
    resource.facilities = params[:facilities]
		update! do |format|
      if resource.errors.empty?
        format.html {redirect_to collection_path}
      else
        flash[:errors] = resource.errors.full_messages
        format.html {redirect_to :back}
      end
    end
	end

	protected
		def collection
			@collection ||= end_of_association_chain.search_by(params).latest.page(page).per(per_page)
		end

    def prepare_types
      @types = PropertyType.roots.where(name: 'Auction Property').pluck(:name)
    end

		def prepare_user
			@users = User.alfa.pluck(:username, :id)
		end

		def prepare_map_location
			if params[:action] == "edit" || params[:action] == "update"
         city = resource.address.city
         @others = Property.joins(:address).where("properties.id != ?", resource.id).filter_by_city(city).check_latlang.map{|l| [l.title, l.address.latitude, l.address.longitude, "#{number_to_currency_br(l.the_price?)} #{l.the_price_status?}", l.type_property]}
       else
         @others = []
       end
		end

    def number_to_currency_br(number)
      number = 0 if number.blank?
      number_to_currency(number, :unit => "Rp ", :separator => ",", :delimiter => ".", precision: 0)
    end

    def prepare_facilities_edit
      @facilities = AssetFacility.latest.where("LOWER(category) LIKE LOWER('%#{resource.type_property}%')")
    end

    def prepare_facilities_new
      @facilities = AssetFacility.latest
    end
end

app/controllers/backend/developers_controller.rb
class Backend::DevelopersController < Backend::ApplicationController
	defaults resource_class: Developer, collection_name: 'developers', instance_name: 'developer'
  before_action :role_required

	add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Developers", :collection_path

  include MultipleAction

	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	protected
		def collection
			@collection ||= end_of_association_chain.search_by(params)
		end
end

app/controllers/backend/feedbacks_controller.rb
class Backend::FeedbacksController < Backend::ApplicationController
  defaults resource_class: Feedback, collection_name: 'feedbacks', instance_name: 'feedback'
  before_action :role_required

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Feedbacks", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/home_controller.rb
class Backend::HomeController < Backend::ApplicationController
	before_filter :prepare_counts!

	add_breadcrumb "Dashboard", :backend_dashboard_path

	def dashboard
	end

	private
		def prepare_counts!
	  end

end

app/controllers/backend/landing_pages_controller.rb
class Backend::LandingPagesController < Backend::ApplicationController
  defaults resource_class: LandingPage, collection_name: 'landing_pages', instance_name: 'landing_page'
  before_action :role_required

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Landing Pages", :collection_path

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  def create
    build_resource
    create! do |format|
      if resource.errors.empty?
        format.html {redirect_to collection_path}
      else
        flash[:errors] = resource.errors.full_messages
        format.html {redirect_to :back}
      end
    end
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/controllers/backend/locations_controller.rb
class Backend::LocationsController < Backend::ApplicationController
	defaults resource_class: Location, collection_name: 'locations', instance_name: 'location'
  before_action :role_required

	add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Locations", :collection_path

  before_filter :prepare_map_location, except: [:index, :destroy]

  include MultipleAction

	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	def create
		build_resource
    resource.user_id = current_user.id
		create! do |format|
      if resource.errors.empty?
        format.html {redirect_to collection_path}
      else
        flash[:errors] = resource.errors.full_messages
        format.html {redirect_to :back}
      end
    end
	end

	def update
		update! do |format|
      if resource.errors.empty?
        format.html {redirect_to collection_path}
      else
        flash[:errors] = resource.errors.full_messages
        format.html {redirect_to :back}
      end
    end
	end

	protected
		def collection
			@collection ||= end_of_association_chain.search_by(params)
		end

		def prepare_map_location
			if params[:action] == "edit" || params[:action] == "update"
         city = resource.address.city
        @others = Location.joins(:address).where("locations.id != ?", resource.id).filter_by_city(city).map{|l| [l.title, l.latitude, l.longitude, l.type_asset]}
       else
         @others = []
       end
		end
end

app/controllers/backend/members_controller.rb
class Backend::MembersController < Backend::ApplicationController
	defaults resource_class: Member, collection_name: 'members', instance_name: 'member'
  before_action :role_required

	add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Members", :collection_path

  include MultipleAction

	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	protected
		def collection
			@collection ||= end_of_association_chain.search_by(params)
		end
end

app/controllers/backend/property_types_controller.rb
class Backend::PropertyTypesController < Backend::ApplicationController
	defaults resource_class: PropertyType, collection_name: 'property_types', instance_name: 'property_type'
  before_action :role_required

	add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Property Types", :collection_path

  include MultipleAction

	def index
		@collection = collection.roots.alfa.page(page).per(per_page)
	end

	protected
		def collection
			@collection ||= end_of_association_chain
		end
end

app/views/backend/auction_properties/_basic_form_apartment.html.erb
<div class="basic-form basic-form-apartment">
  <h3>Basic Apartment</h3>
  <hr>
  <div class="row">
    <div class="col-md-6">
      <div class="row">
        <div class="col-xs-12">
          <div class="form-group">
            <h6>Document</h6>
            <%= basic.select :document, Document.to_a, {prompt: 'Select'}, {class: 'form-control'} %>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group">
            <h6>Building Area in (m<sup>2</sup>)</h6>
            <%= basic.number_field :building_area, class: 'form-control', placeholder: 'ex. 1000' %>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group">
            <h6>Entrance Facing</h6>
            <%= basic.select :facing, Facing.to_a, {prompt: 'Select'}, {class: 'form-control'} %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-xs-6">
          <div class="form-group">
            <h6>Lines Phone</h6>
            <%= basic.number_field :phone_lines, class: 'form-control' %>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group">
            <h6>Bedrooms</h6>
            <%= basic.number_field :bedrooms, class: 'form-control' %>
          </div>
        </div>
        <div class="col-xs-4">
          <div class="form-group">
            <h6>Bathrooms</h6>
            <%= basic.number_field :bathrooms, class: 'form-control' %>
          </div>
        </div>
        <div class="col-xs-4">
          <div class="form-group">
            <h6>Parking</h6>
            <%= basic.number_field :parking, class: 'form-control' %>
          </div>
        </div>
        <div class="col-xs-4">
          <div class="form-group">
            <h6>Floor</h6>
            <%= basic.number_field :floor, class: 'form-control' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/backend/auction_properties/_basic_form_factory.html.erb
<div class="basic-form basic-form-factory">
  <h3>Basic Factory</h3>
  <hr>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <h6>Document</h6>
        <%= basic.select :document, Document.to_a, {prompt: 'Select'}, {class: 'form-control'} %>
      </div>
      <div class="form-group">
        <h6>Land Area in m<sup>2</sup></h6>
        <%= basic.number_field :surface_area, class: 'form-control', placeholder: 'ex. 1000m' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <h6>Year Built</h6>
        <%= basic.select :age, options_for_select((1950..Time.now.year).to_a, basic.object.age), {prompt: 'Select Year'}, {class: 'form-control select2', placeholder: 'ex. 2015'} %>
      </div>
      <div class="form-group">
        <h6>Electricity</h6>
        <%= basic.text_field :electricity, class: 'form-control', placeholder: 'ex. 300 watt' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="row">
        <div class="col-xs-6">
          <div class="form-group">
            <h6>Lines Phone</h6>
            <%= basic.number_field :phone_lines, class: 'form-control' %>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group">
            <h6>Entrance Facing</h6>
            <%= basic.select :facing, Facing.to_a, {prompt: 'Select'}, {class: 'form-control'} %>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="form-group">
            <h6>Building Area in m<sup>2</sup></h6>
            <%= basic.number_field :building_area, class: 'form-control', placeholder: 'ex. 600' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/backend/auction_properties/_basic_form_land.html.erb
<div class="basic-form basic-form-land">
  <h3>Basic Land</h3>
  <hr>
  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <h6>Document</h6>
        <%= basic.select :document, Document.to_a, {prompt: 'Select'}, {class: 'form-control'} %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <h6>Land Area in (m<sup>2</sup>)</h6>
        <%= basic.number_field :surface_area, class: 'form-control', placeholder: 'ex. 1000' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <h6>Long Land in (m<sup>2</sup>)</h6>
        <%= basic.number_field :long_land, class: 'form-control', placeholder: 'ex. 200' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <h6>Width Land in (m<sup>2</sup>)</h6>
        <%= basic.number_field :width_land, class: 'form-control', placeholder: 'ex. 800' %>
      </div>
    </div>
  </div>
</div>

app/views/backend/auction_properties/_basic_form_office.html.erb
<div class="basic-form basic-form-office">
  <h3>Basic Office</h3>
  <hr>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <h6>Document</h6>
        <%= basic.select :document, Document.to_a, {prompt: 'Select'}, {class: 'form-control'} %>
      </div>
      <div class="form-group">
        <h6>Building Area in (m<sup>2</sup>)</h6>
        <%= basic.number_field :building_area, class: 'form-control', placeholder: 'ex. 1000' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <h6>Year Built</h6>
        <%= basic.select :age, options_for_select((1950..Time.now.year).to_a, basic.object.age), {prompt: 'Select Year'}, {class: 'form-control select2', placeholder: 'ex. 2015'} %>
      </div>
      <div class="form-group">
        <h6>Electricity</h6>
        <%= basic.text_field :electricity, class: 'form-control', placeholder: 'ex. 300 watt' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <h6>Lines Phone</h6>
        <%= basic.number_field :phone_lines, class: 'form-control' %>
      </div>
      <div class="form-group">
        <h6>Entrance Facing</h6>
        <%= basic.select :facing, Facing.to_a, {prompt: 'Select'}, {class: 'form-control'} %>
      </div>
    </div>
  </div>
</div>

app/views/backend/auction_properties/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-4">
        <h6>User</h6>
        <%= f.select :user_id, User.pluck(:username, :id), {prompt: 'Select User'}, {class: 'form-control select2', required: true} %>
         <div class="break"></div>
      </div>
    </div>
    <div class="row">
      <% @types.each do |key, value| %>
        <div class="col-md-12">
          <div class="well">
            <center>
              <h2><%= key %></h2>
              <p><%= f.radio_button :category, key, required: true, class: 'categories_select', 'data-node' => "#{resource.class.to_s.downcase}" %></p>
            </center>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <h6>Type</h6>
          <% type_properties = f.object.category.present? ? (PropertyType.find_by(name: f.object.category).try(:children).pluck('name') rescue PropertyType.pluck(:name)) : PropertyType.none rescue [] %>
          <div class="category-container">
            <%= f.select :type_property, options_for_select(type_properties, f.object.type_property), {prompt: 'Select Type'}, class: 'select2 form-control type_properties_select', required: true %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <h6>Title</h6>
          <%= f.text_field :title, class: 'form-control', required: true, maxlength: 50 %>
        </div>
      </div>
      <%= f.fields_for :auction do |auction| %>
        <%= render partial: 'form_auction', locals: {f: auction} %>
      <% end %>
    </div>
    <div class="break"></div>
    <div class="row">
      <div class="col-md-6">
        <div class="well">
          <center>
            <p>Sold Out</p>
            <p><%= f.check_box :sold_out %></p>
          </center>
        </div>
      </div>
      <div class="col-md-6">
        <div class="well">
          <center>
            <p>Featured</p>
            <p><%= f.check_box :featured %></p>
          </center>
        </div>
      </div>
    </div>
    <div class="break"></div>
  </div>
</div>

<div class="section-basic-form">
  <%= f.fields_for :basic_property do |basic| %>
    <%= render partial: 'form_basic', locals: {f: f, basic: basic} %>
  <% end %>
</div>

<div class="row">
  <div class="col-md-12">
    <h3>Facilities</h3>
    <hr>
    <div class="facility" data-url="<%= get_societies_url%>">
      <% @facilities.each_with_index do |s| %>
        <% if resource.present? %>
          <%= render partial: 'properties/auction_facility_fields', locals: {s: s} %>
        <% else %>
          <%= render partial: 'properties/auction_facility_fields_new', locals: {s: s} %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="break"></div>

<div class="row">
  <div class="col-md-12">
    <h3>Gallery</h3>
    <hr>
    <div class="setup-content">
      <ul class="choice-gallery-form">
        <%= f.fields_for :galleries do |g| %>
          <%= render 'gallery_fields', f: g %>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="break"></div>

<%= f.fields_for :address do |address| %>
  <%= render partial: 'form_address', locals: {address: address} %>
<% end %>

app/views/backend/auction_properties/index.html.erb
<div class="col-md-12">
	<%= render 'backend/shareds/search_form_property' %>
	<%= form_for :multiple, url: "#{collection_path}/do_multiple_act", method: 'post' do %>
		<div class="widget">
			<%= render partial: 'backend/shareds/prepare_table', locals: {table_name: 'Auction Properties', button_name: 'Auction Property', add_method: true} %>
			<div class="widget-content">
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr>
								<th width="1%"></th>
								<th>Flate Id</th>
								<th>Title</th>
								<th>Status</th>
								<th>User</th>
								<th>Created At</th>
								<th>Start At - Expired At</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
							<% @collection.each_with_index do |resource, index| %>
								<tr>
									<td><%= check_box_tag "ids[]", resource.id %></td>
									<td><%= resource.code %></td>
									<td><%= link_to resource.title, property_path(resource) %> <%= resource.featured? %></td>
									<td>
										<% if resource.sold? %>
											<%= resource.sold_label? %>
										<% else %>
											<%= resource.active? %>
										<% end %>
									</td>
									<td><%= link_to resource.user.username, user_path(resource.user) if resource.user %></td>
									<td><%= resource.created_at.strftime("%B, %d, %Y") if resource.created_at.present? %></td>
									<td>
										<% if resource.started_at.present? %>
											<b>Start:</b> <%= resource.started_at.strftime("%B, %d, %Y")%><br>
										<% end %>
										<% if resource.expired_at.present? %>
											<b>Expired:</b> <%= resource.expired_at.strftime("%B, %d, %Y") %>
										<% end %>
									</td>
									<td>
										<%= render partial: 'backend/shareds/prepare_action',
	                    locals: { resource: resource, confirmation: "Are you sure delete this #{resource.id}", no_show: false } %>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div>

				<div class="widget-foot">
					<div class="pull-right">
						<%= paginate @collection %>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	<% end %>
</div>