config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root 'publics#home'

  resources :properties do
    collection do
      get :auction
      get :featureds, to: 'properties#featured'
      get 'wishlist/:id', to: 'properties#wishlist', as: 'wishlist'
      post :checkout_bid
    end
  end

  resources :projects do
    collection { get :featureds, to: 'projects#featureds' }
  end
  resources :users, only: [:show] do
    member do
      get :about_company
      get 'reviews', to: 'users#reviews'
      delete 'reviews/:rate_id', to: 'users#delete_reviews', as: 'delete_rate'
      post 'reviews', to: 'reviews#create'
    end
  end
  resources :landing_pages, only: [:show]
  resources :inquiries
  resources :feedbacks, only: [:create]
  resources :reports, only: [:create]
  resources :schedule_visits, only: [:create]

  get 'map',                          to: 'properties#map',             as: 'map'
  get 'list',                         to: 'properties#list',            as: 'list'
  get 'package',                      to: 'publics#package',            as: 'package'
  get 'get_societies',                to: 'publics#get_societies',      as: 'get_societies'

  get 'get_assets',                   to: 'xhrs#get_assets',            as: 'get_assets'
  get 'get_assets_property',          to: 'xhrs#get_assets_property',   as: 'get_assets_property'
  post 'save_assets_property',        to: 'xhrs#save_assets_property',  as: 'save_assets_property'
  get 'get_project_assets',           to: 'xhrs#get_project_assets',    as: 'get_project_assets'
  get 'get_assets_project',           to: 'xhrs#get_assets_projects',   as: 'get_assets_project'
  post 'save_assets_project',         to: 'xhrs#save_assets_project',   as: 'save_assets_project'
  get 'get_categories',               to: 'publics#get_categories',     as: 'get_categories'
  get 'cities_tag',                   to: 'publics#cities_tag',         as: 'cities_tag'
  get 'cities',                       to: 'xhrs#cities',                as: 'cities'
  get 'subdistricts',                 to: 'xhrs#subdistricts',          as: 'subdistricts'
  get 'village',                      to: 'xhrs#village',               as: 'village'
  get 'area',                         to: 'xhrs#area',                  as: 'area'
  get 'get_by_city',                  to: 'xhrs#get_by_city',           as: 'get_by_city'
  get 'get_properties_search',        to: 'xhrs#get_properties_search', as: 'get_properties_search'
  get '/get_detail_profile_property', to: 'xhrs#get_detail_properties', as: 'get_detail_profile_property'
  get '/get_detail_profile_project',  to: 'xhrs#get_detail_projects',   as: 'get_detail_profile_project'
  get '/label_packages',              to: 'xhrs#label_packages',        as: 'label_packages'

  get "autocomplete_region", to: "xhrs#autocomplete_region"
  get "autocomplete_auction_region", to: "xhrs#autocomplete_auction_region"

  resources :xhrs do
    collection do
      get :get_categories
      get :get_facilities
    end
  end

  namespace :backend do
    # The Role
    resources :roles, except: :show do
      patch 'change', on: :member
      resources :sections, controller: 'role_sections', only: :none do
        collection do
          post :create
          post :create_rule
          post :create_field

        end

        member do
          put :rule_on
          put :rule_off

          delete :destroy
          delete :destroy_rule
        end
      end
    end

    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :admins
    resources :members do
      collection do
        post :do_multiple_act
      end
    end
    resources :agents do
      collection do
        post :do_multiple_act
      end
    end
    resources :packages do
      collection do
        post :do_multiple_act
      end
    end
    resources :order_user_packages do
      member do
        patch '/confirmations', to: 'order_user_packages#confirmations'
      end
      collection do
        post '/multiple_confirmations', to: 'order_user_packages#multiple_confirmations'
      end
    end
    resources :developers do
      collection do
        post :do_multiple_act
      end
    end
    resources :properties do
      collection do
        post :do_multiple_act
        get :import, to: 'properties#import'
        post :do_import, to: 'properties#do_import'
        post :import, to: 'properties#do_import'
      end
    end
    resources :auction_properties do
      collection do
        post :do_multiple_act
      end
    end
    resources :property_types do
      collection do
        post :do_multiple_act
      end
    end
    resources :asset_facilities do
      collection do
        post :do_multiple_act
      end
    end
    resources :projects do
      collection do
        post :do_multiple_act
        get :import, to: 'projects#import'
        post :do_import, to: 'projects#do_import'
        post :import, to: 'projects#do_import'
      end
    end
    resources :locations do
      collection do
        post :do_multiple_act
      end
    end
    resources :supporteds do
      collection do
        post :do_multiple_act
      end
    end
    resources :testimonials do
      collection do
        post :do_multiple_act
      end
    end
    resources :feedbacks do
      collection do
        post :do_multiple_act
      end
    end
    resources :reports do
      collection do
        post :do_multiple_act
      end
    end
    resources :sold_reports do
      collection do
        post :do_multiple_act
      end
    end
    resources :regions
    resources :landing_pages
    resources :web_settings
  end

  namespace :userpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members do
      member do
        put :upgrade
      end
    end
    resources :agents, only: [:edit, :update, :show]
    resources :wishlists
    resources :inquiries
    resources :notifications
    resources :properties do
      member do
        put :renew
      end
      collection do
        post :do_report_sold
      end
    end
    resources :sold_reports
    resources :packages do
      collection do
        get :invoices
      end
      member do
        get :invoice
      end
    end
  end

  namespace :developerpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :developers, only: [:edit, :update, :show]
    resources :wishlists
    resources :inquiries
    resources :notifications
    resources :projects
  end
end

app/controllers/backend/home_controller.rb
class Backend::HomeController < Backend::ApplicationController
	before_filter :prepare_counts!

	add_breadcrumb "Dashboard", :backend_dashboard_path

	def dashboard
	end

	private
		def prepare_counts!
	  end

end

app/controllers/developerpage/home_controller.rb
class Developerpage::HomeController < Developerpage::ApplicationController
	add_breadcrumb "Dashboard", :developerpage_dashboard_path

	def dashboard
	end

end

app/controllers/userpage/home_controller.rb
class Userpage::HomeController < Userpage::ApplicationController
	add_breadcrumb "Dashboard", :userpage_dashboard_path

	def dashboard
	end

end

app/views/shareds/home/_carousel.html.erb
<section>
  <!-- The carousel -->
  <div id="transition-timer-carousel" class="home-carousel carousel slide transition-timer-carousel" data-ride="carousel">

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <% @setting.galleries.each_with_index do |f, index| %>
        <% cache ["home_carousel_#{f.id}_#{f.updated_at.to_time.to_i}"] do %>
          <div class="item <%= 'active' if index == 1 %>">
            <%= image_tag f.file.url %>
          </div>
        <% end %>
      <% end %>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#transition-timer-carousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#transition-timer-carousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>

    <!-- Timer "progress bar" -->
    <hr class="transition-timer-carousel-progress-bar animate" />

    <div class="box-search-form-multiaction">
      <div class="main-text">
        <div class="text-center">
          <div class="col-md-10 col-md-offset-1">
            <div class="title-search-homepage">
              <h2 class="h-search-multiaction">Look Up Places to Buy</h2>
            </div>
            <div class="search-form-multiaction">
              <!-- Nav tabs -->
              <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active">
                  <a href="#buy" aria-controls="sell" role="tab" data-toggle="tab" data-value="Look Up Places to Buy">Buy</a>
                </li>
                <li role="presentation">
                  <a href="#rent" aria-controls="rent" role="tab" data-toggle="tab" data-value="Look Up Places to Rent">Rent</a>
                </li>
                <li role="presentation">
                  <a href="#projects" aria-controls="projects" role="tab" data-toggle="tab" data-value="Look Up Places Projects">New Projects</a>
                </li>
                <li role="presentation">
                  <a href="#auction" aria-controls="auction" role="tab" data-toggle="tab" data-value="Look Up Places to Bid Auction">Auction</a>
                </li>
              </ul>

              <!-- Tab panes bottom -->
              <div class="form-searching">
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane active" id="buy">
                    <%= form_for :search, url: properties_path, html:{class: 'form-inline', id: 'property-search', name: 'search'}, method: 'get' do %>
                      <div class="input-group">
                        <%= hidden_field_tag :category, 'Sell' %>
                        <%= autocomplete_field_tag :region_display_name, "", autocomplete_region_path, placeholder: "Search by locality", class: 'form-control by-locality', value: params[:region_display_name] %>
                        <% type_property_buy = PropertyType.find_by(name: 'Sell').try(:children).pluck('name') %>
                        <%= select_tag :type_property, options_for_select(type_property_buy, params[:type_property]), prompt: 'Select Type Property', class: 'form-control type_properties_select_search by-keywords' %>
                        <span class="input-group-btn">
                          <button class="btn btn-lg btn-info by-search" type="submit">
                            <i class="fa fa-search"></i>
                          </button>
                        </span>
                      </div>
                    <% end %>
                  </div>
                  <div role="tabpanel" class="tab-pane" id="rent">
                    <%= form_for :search, url: properties_path, html:{class: 'form-inline', id: 'property-search', name: 'search'}, method: 'get' do %>
                      <div class="input-group">
                        <%= hidden_field_tag :category, 'Rent' %>
                        <%= autocomplete_field_tag :region_display_name, "", autocomplete_region_path, placeholder: "Search by locality", class: 'form-control by-locality', value: params[:region_display_name] %>
                        <% type_property_buy = PropertyType.find_by(name: 'Rent').try(:children).pluck('name') %>
                        <%= select_tag :type_property, options_for_select(type_property_buy, params[:type_property]), prompt: 'Select Type Property', class: 'form-control type_properties_select_search by-keywords' %>
                        <span class="input-group-btn">
                          <button class="btn btn-lg btn-info by-search" type="submit">
                            <i class="fa fa-search"></i>
                          </button>
                        </span>
                      </div>
                    <% end %>
                  </div>
                  <div role="tabpanel" class="tab-pane" id="projects">
                    <%= form_for :search, url: projects_path, html:{class: 'form-inline', id: 'property-search', name: 'search'}, method: 'get' do %>
                      <div class="input-group">
                        <%= hidden_field_tag :category, 'New Project' %>
                        <%= autocomplete_field_tag :region_display_name, "", autocomplete_region_path, placeholder: "Search by locality", class: 'form-control by-locality', value: params[:region_display_name] %>
                        <% type_property_buy = PropertyType.find_by(name: 'New Project').try(:children).pluck('name') %>
                        <%= select_tag :type_project, options_for_select(type_property_buy, params[:type_project]), prompt: 'Select Type Property', class: 'form-control type_properties_select_search by-keywords' %>
                        <span class="input-group-btn">
                          <button class="btn btn-lg btn-info by-search" type="submit">
                            <i class="fa fa-search"></i>
                          </button>
                        </span>
                      </div>
                    <% end %>
                  </div>
                  <div role="tabpanel" class="tab-pane" id="auction">
                    <%= form_for :search, url: properties_path, html:{class: 'form-inline', id: 'property-search', name: 'search'}, method: 'get' do %>
                      <div class="input-group">
                        <%= hidden_field_tag :category, 'Auction Property' %>
                        <%= autocomplete_field_tag :region_auction_display_name, params[:region_auction_display_name], autocomplete_auction_region_path, class: 'form-control by-full-locality', placeholder: 'By address, city, state, ZIP code, Property Id' %>
                        <span class="input-group-btn">
                          <button class="btn btn-lg btn-info by-search" type="submit">
                            <i class="fa fa-search"></i>
                          </button>
                        </span>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- <div class="grid-category-menu">
    <ul>
      <li>
        <%= link_to properties_path(category: 'Rent') do %>
          <i class="fa fa-key"></i>
          <span clas="title">RENT</span>
        <% end %>
      </li>
      <li>
        <%= link_to properties_path(category: 'Sell') do %>
          <i class="fa fa-home"></i>
          <span clas="title">SELL</span>
        <% end %>
      </li>
      <li>
        <%= link_to auction_properties_path do %>
          <i class="fa fa-institution"></i>
          <span clas="title">AUCTION PROPERTY</span>
        <% end %>
      </li>
      <li>
        <%= link_to projects_path do %>
          <i class="fa fa-building"></i>
          <span clas="title">NEW PROJECTS</span>
        <% end %>
      </li>
    </ul>
  </div> -->
</section>

app/views/shareds/home/_group_partner.html.erb
<section class="section group-partner">
	<div class="container">
		<div class="line-through">
			<p><span>Supported By</span></p>
		</div>
		<div id="media" class="carousel carousel_supporteds slide media-carousel">
			<div class="carousel-inner">
				<% @supporteds.each do |f| %>
					<% cache ["supporteds_#{f.id}_#{f.updated_at.to_time.to_i}"] do %>
						<div class="supporteds-item col-md-2">
							<%= image_tag "#{f.logo.url(:small)}", alt: '#{ f.title }', class: 'img-responsive' %>
						</div>
					<% end %>
				<% end %>
			</div>
			<a data-slide="prev" href="#media" class="left carousel-control">‹</a>
			<a data-slide="next" href="#media" class="right carousel-control">›</a>
		</div>
	</div>
</section>

app/views/shareds/home/_paralax.html.erb
<section class="parallax">
	<div class="ha-bg-parallax text-center">
		<div class="ha-parallax-body">
			<div class="ha-content ha-content-whitecolor">
				"PROPEDIA is a market / Indonesia's largest online mall that lets individuals and business owners in Indonesia to open and manage their online store is easy and free."
			</div>
			<div class="ha-parallax-divider-wrapper">
				<span class="ha-diamond-divider-md img-responsive"></span>
			</div>
			<div class="ha-heading-parallax">CEO PROPEDIA</div>
		</div>
	</div>
</section>

app/views/shareds/home/_popular_locations.html.erb
<section class="section grey">
	<div class="container">
		<div class="row">
			<div class="line-through">
				<p><span class="grey">Featured Locations</span></p>
			</div>
			<div class="top-list-cities-wrapper col-md-12">
				<% @regions.each do |region| %>
					<% region_display_name = "#{region.try(:name)}, #{region.try(:parent).try(:name)}" %>
					<% cache ["featured_regions_#{region.id}_#{region.updated_at.to_time.to_i}"] do %>
						<div class="col-md-4 col-sm-12 col-xs-12">
							<%= link_to properties_path(region_display_name: region_display_name) do %>
								<figure>
									<%= image_tag region.image.url(:medium), class: 'img-responsive' %>
									<span><%= region.name %>, <%= region.root.name if region.root.present? %></span>
									<figcaption>
										<div><%= region.name %>, <%= region.root.name if region.root.present? %></div>
									</figcaption>
								</figure>
							<% end %>
						</div>
					<% end %>
				<% end %>
			</div>
			<%= link_to 'View More', properties_path, class: "btn btn-more-info" %>
		</div>
	</div>
</section>

app/views/shareds/home/_testimonials.html.erb
<section class="section green">
	<div class="container">
		<div class="row">
			<h2 align="center">WHAT DRIVES US</h2>
			<div class="col-md-12" data-wow-delay="0.2s">
				<div class="carousel slide" data-ride="carousel" id="quote-carousel">
					<ol class="carousel-indicators">
						<% @testimonials.each_with_index do |testimonial,index| %>
							<% cache ["ava_testimonials_#{testimonial.id}_#{testimonial.updated_at.to_time.to_i}"] do %>
								<li data-target="#quote-carousel" data-slide-to="0" class="<%= 'active' if index == 1 %>">
									<%= image_tag "#{testimonial.try(:user).try(:profile).try(:avatar).url(:small)}", class: 'img-responsive' if testimonial.user.present? %>
								</li>
							<% end %>
						<% end %>
					</ol>

					<div class="carousel-inner text-center">
						<% @testimonials.each_with_index do |testimonial,index| %>
							<% cache ["testimonials_#{testimonial.id}_#{testimonial.updated_at.to_time.to_i}"] do %>
								<div class="item <%= 'active' if index == 1 %>">
									<blockquote>
										<div class="row">
											<div class="col-sm-8 col-sm-offset-2">
												<p><%= testimonial.message.html_safe if testimonial.message.present? %></p>
												<small>
													@<%= testimonial.email %> | <%= testimonial.name %>
												</small>
											</div>
										</div>
									</blockquote>
								</div>
							<% end %>
						<% end %>
					</div>

					<a data-slide="prev" href="#quote-carousel" class="left carousel-control">
						<i class="fa fa-chevron-left"></i>
					</a>
					<a data-slide="next" href="#quote-carousel" class="right carousel-control">
						<i class="fa fa-chevron-right"></i>
					</a>
				</div>
			</div>
		</div>
		</div>
	</div>
</section>